name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install Roc
        uses: hasnep/setup-roc@main
        with:
          roc-version: nightly

      - name: Install expect
        run: sudo apt install -y expect

      - name: Test the library
        run: find . -name "*.test.roc" -exec roc test "{}" --linker=legacy \;
